name: ci
on: [push]

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: self test
        uses: ./
        with:
          ak: ${{ secrets.QINIU_AK }}
          sk: ${{ secrets.QINIU_SK }}
          domain: '*.fox.mn'
          update-domains: |
            .fox.mn | https | http2
          debug: 'yes'
          cert: ${{ secrets.FULL_CHAIN }}
          key: ${{ secrets.DOMAIN_KEY }}
          
