name: ci
on: [push]

jobs:
  study:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: self test
        uses: ./
        with:
          ak: ${{ secrets.QINIU_AK }}
          sk: ${{ secrets.QINIU_SK }}
          domain: '*.fox.mn'
          update-domains: |
            qn.fox.mn
            .fox.mn | true
            cloudnative.fox.mn | true
          debug: 'yes'
          cert: |
            -----BEGIN CERTIFICATE-----
            MIIFKTCCBBGgAwIBAgITAPoxL7+xLFck0uOSltr6uDS+bTANBgkqhkiG9w0BAQsF
            ADAiMSAwHgYDVQQDDBdGYWtlIExFIEludGVybWVkaWF0ZSBYMTAeFw0xOTEyMDUw
            NzEwMTBaFw0yMDAzMDQwNzEwMTBaMBMxETAPBgNVBAMMCCouZm94Lm1uMIIBIjAN
            BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArEahi1SlmZcGZd1IEcuTHs8V7hTB
            caUmsiU9pvhV8rWHvmqPg06izkUkihY20aYLyfRDY6pbZvfBSHrSrnBO+rn9NCSx
            FMI6ZqpnipMc+/88DQ3uh0f4cGaaXBKiFTpl3TbDFZJKm2ya8y00oCVyqaoioZtO
            S/vDKjuHDIqCizDp+Avyu6xpb6vE/VjtJS/+MVv6XwSmH8HZ/NUV+UsD0f3lIzje
            kRb70E8TY4Z3gzDyPczyg+I5c2R8ch90YYpnYdn5vHNW9nCuu29L8z66Dm8lbgRE
            8ledU8ZQV4axX0GXWYE3OaKNbpNpXEz727n1YrPso08C99DeyYglfeRL6wIDAQAB
            o4ICZTCCAmEwDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggr
            BgEFBQcDAjAMBgNVHRMBAf8EAjAAMB0GA1UdDgQWBBTcijMaK4zjN+uanH28Og1i
            p+t/ajAfBgNVHSMEGDAWgBTAzANGuVggzFxycPPhLssgpvVoOjB3BggrBgEFBQcB
            AQRrMGkwMgYIKwYBBQUHMAGGJmh0dHA6Ly9vY3NwLnN0Zy1pbnQteDEubGV0c2Vu
            Y3J5cHQub3JnMDMGCCsGAQUFBzAChidodHRwOi8vY2VydC5zdGctaW50LXgxLmxl
            dHNlbmNyeXB0Lm9yZy8wEwYDVR0RBAwwCoIIKi5mb3gubW4wTAYDVR0gBEUwQzAI
            BgZngQwBAgEwNwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nw
            cy5sZXRzZW5jcnlwdC5vcmcwggEEBgorBgEEAdZ5AgQCBIH1BIHyAPAAdgDGPyIY
            w31WpqoGtZbajlPU1xVtHpusjkTSIC3mTWnZ3AAAAW7VG/u0AAAEAwBHMEUCIGwC
            d3d8So2P6X+d00A6K+rXHLWwa0GBtVDOzRtI714LAiEA5sor0piScO75Bsz4f6Xz
            W6nfA4OSwy2uVH/dueTmZ2oAdgCwzIPlpfl9a698CcwoSQSHKsfoixMsY1C3xv0m
            4WxsdwAAAW7VG/utAAAEAwBHMEUCIFZPA0su2gj7Q6OMAQ41z1Mn6AF0aI5RaQhm
            +S9zBCzMAiEA3eo22c4QiHsiTNTSvUrtKXdVxLeCBv5XsGVd+hvj3howDQYJKoZI
            hvcNAQELBQADggEBABT0sMHNTpSZZwcH9tG/Bh/ped0xtYi/M3a8uion1CwTci4P
            7SWKHT7ZPffAAoLEfFneJkNVITKv8AFst131w27gdM9NAiCCERX3W9gQD6YFiVNg
            S31CvWvvOMxMkeMshpUmGQa3dlCFSCjKZVPf88G1JqomAbw2Hr7XrvcRuvRg9Srt
            Y1QOgSFgCgA9Qvgh7ojpI4k6UfnHG34YznC8PUjnNTRGMEMPHK7ppHRMSPsP4TvC
            XjDpU4SU6LmEEwUJuu6ABI2wXYtIHRcWa9dVY7Tjlss9GrvcgECZLx0XhwWv8BZT
            x8s1mUJoYGRLfrzZ4TiwhXBBBJc19v+urwLfMwc=
            -----END CERTIFICATE-----

            -----BEGIN CERTIFICATE-----
            MIIEqzCCApOgAwIBAgIRAIvhKg5ZRO08VGQx8JdhT+UwDQYJKoZIhvcNAQELBQAw
            GjEYMBYGA1UEAwwPRmFrZSBMRSBSb290IFgxMB4XDTE2MDUyMzIyMDc1OVoXDTM2
            MDUyMzIyMDc1OVowIjEgMB4GA1UEAwwXRmFrZSBMRSBJbnRlcm1lZGlhdGUgWDEw
            ggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDtWKySDn7rWZc5ggjz3ZB0
            8jO4xti3uzINfD5sQ7Lj7hzetUT+wQob+iXSZkhnvx+IvdbXF5/yt8aWPpUKnPym
            oLxsYiI5gQBLxNDzIec0OIaflWqAr29m7J8+NNtApEN8nZFnf3bhehZW7AxmS1m0
            ZnSsdHw0Fw+bgixPg2MQ9k9oefFeqa+7Kqdlz5bbrUYV2volxhDFtnI4Mh8BiWCN
            xDH1Hizq+GKCcHsinDZWurCqder/afJBnQs+SBSL6MVApHt+d35zjBD92fO2Je56
            dhMfzCgOKXeJ340WhW3TjD1zqLZXeaCyUNRnfOmWZV8nEhtHOFbUCU7r/KkjMZO9
            AgMBAAGjgeMwgeAwDgYDVR0PAQH/BAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8CAQAw
            HQYDVR0OBBYEFMDMA0a5WCDMXHJw8+EuyyCm9Wg6MHoGCCsGAQUFBwEBBG4wbDA0
            BggrBgEFBQcwAYYoaHR0cDovL29jc3Auc3RnLXJvb3QteDEubGV0c2VuY3J5cHQu
            b3JnLzA0BggrBgEFBQcwAoYoaHR0cDovL2NlcnQuc3RnLXJvb3QteDEubGV0c2Vu
            Y3J5cHQub3JnLzAfBgNVHSMEGDAWgBTBJnSkikSg5vogKNhcI5pFiBh54DANBgkq
            hkiG9w0BAQsFAAOCAgEABYSu4Il+fI0MYU42OTmEj+1HqQ5DvyAeyCA6sGuZdwjF
            UGeVOv3NnLyfofuUOjEbY5irFCDtnv+0ckukUZN9lz4Q2YjWGUpW4TTu3ieTsaC9
            AFvCSgNHJyWSVtWvB5XDxsqawl1KzHzzwr132bF2rtGtazSqVqK9E07sGHMCf+zp
            DQVDVVGtqZPHwX3KqUtefE621b8RI6VCl4oD30Olf8pjuzG4JKBFRFclzLRjo/h7
            IkkfjZ8wDa7faOjVXx6n+eUQ29cIMCzr8/rNWHS9pYGGQKJiY2xmVC9h12H99Xyf
            zWE9vb5zKP3MVG6neX1hSdo7PEAb9fqRhHkqVsqUvJlIRmvXvVKTwNCP3eCjRCCI
            PTAvjV+4ni786iXwwFYNz8l3PmPLCyQXWGohnJ8iBm+5nk7O2ynaPVW0U2W+pt2w
            SVuvdDM5zGv2f9ltNWUiYZHJ1mmO97jSY/6YfdOUH66iRtQtDkHBRdkNBsMbD+Em
            2TgBldtHNSJBfB3pm9FblgOcJ0FSWcUDWJ7vO0+NTXlgrRofRT6pVywzxVo6dND0
            WzYlTWeUVsO40xJqhgUQRER9YLOLxJ0O6C8i0xFxAMKOtSdodMB3RIwt7RFQ0uyt
            n5Z5MqkYhlMI3J1tPRTp1nEt9fyGspBOO05gi148Qasp+3N+svqKomoQglNoAxU=
            -----END CERTIFICATE-----


          key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpQIBAAKCAQEArEahi1SlmZcGZd1IEcuTHs8V7hTBcaUmsiU9pvhV8rWHvmqP
            g06izkUkihY20aYLyfRDY6pbZvfBSHrSrnBO+rn9NCSxFMI6ZqpnipMc+/88DQ3u
            h0f4cGaaXBKiFTpl3TbDFZJKm2ya8y00oCVyqaoioZtOS/vDKjuHDIqCizDp+Avy
            u6xpb6vE/VjtJS/+MVv6XwSmH8HZ/NUV+UsD0f3lIzjekRb70E8TY4Z3gzDyPczy
            g+I5c2R8ch90YYpnYdn5vHNW9nCuu29L8z66Dm8lbgRE8ledU8ZQV4axX0GXWYE3
            OaKNbpNpXEz727n1YrPso08C99DeyYglfeRL6wIDAQABAoIBAQCEcYigZWMqwUDZ
            71UI2Ukx1mM1th9CD4XAT4EmbKUnAwhpC+NpP3tKuT1uK8XZR56olHF6ne3HK5Ic
            9tAh65XMjFBtVggNvYTIiRkxIAiYc5DnOF65AkutnjPttSWGzG6jswYn/1/8PXKi
            oY5j0GZmqbYWKB/5qoRQY5NfwNy7xIwm66SS/F6umPg5vg+U1/mGLhMzotGTX3KA
            vZvFDVh6c9NQOXTJ6T6riruT7usgQOQxVs6HxUPU4hdOlJ9UVkIumQbrhQC3I7VB
            afMoZ9mNjt3uLT0qbUKE6kJUhhj8LIl+xJTMj+M3Zq3i5W7MeY9ynGTn876ya6Od
            4v2gq7oBAoGBANW9EPWaQujcRBTqiI1w5q83+dQIa0/cnhvXJSceisdAevsRcfwj
            69UZjhrmFWWw+LhtMwmF31WfbAaUi9b/+DuT2j2Oau5/PFzgVGcXgSPrv1RK8mc0
            S5nedfChg7WTjkGGrH8OdHcmoq2jxDqDe0qsPJH+VbSrNpX2vHWxIb97AoGBAM5W
            00ITgXnalMWvMeGZlT82UQeuXiCTX4vn0hhNQAvAW0DfY9dFlmr6WBAnYKcVjXt9
            it8ABj7T2/HrVhWnNoSOCytzUUSiRMKBcKM9pVm0kdd+OgzGCs9BYeWccSbe8IWm
            NZsPG/WQKXNmfXJQze41JV6v56GDv/mX0p6gu0JRAoGBAM8AJ9+lQe3h/XHAXvWV
            BWVnMeafLMcQpHPUHuBPHRqyISjtEVaft3QQJud4M/rjtU5wO8CaTdzP5EBPN0vH
            ZbLVk8SQHJHU2jIc9MFPKzwNwqQxXaiEJj/kCpc85aFCQcDGXGNFLZiD64N9mrsM
            wahlPNgr2Pd75gbBCm51WXjnAoGAR/xil5rWgPyRCqakcGB0gSkh+9wJWrQPkW+/
            DFtnDLJ/I5LL8j6Ey62rK3eRcLlEMuEJoeMQSrr+8Nd5oPRFQNmNbAs/PwKdmn4u
            HcVT+ofUmamf9vTgsI3O6Zw6naUJpJbn/MC4sGMrEueevFMUhRZlgzM7TE36m8kr
            4cuRiQECgYEAkMqO7ysDXaLociKrJ10exG7cYXU0LOhoWqaCGsdbgh82cA8aOZDH
            MvRDqzhB55MEhejZUTDFLhp45SKlWUvAFrmQIrLfWrLi4Igha/nfl4MwAKsg7ilf
            tU5jzfH2Vm5VF5cEz/GmegCGx83jYcTh7jDuw/nXSOsm81CFomjDatY=
            -----END RSA PRIVATE KEY-----

          

          
